### PR TITLE
assert_ouput: now also print the command that was run

### PR DESCRIPTION
**Pull request by thomasleveil**
Using the stdlib, while the output of failing test is much better than without stdlib, it still can display more useful info. 

For instance, I have a test which is written as:

``` bash
@test "start web container for http://1.bats/" {
    start_web_container 1
}


function start_web_container {
    local id=$1
    docker rm -f bats-web${id} ||:
    run docker run -d --name bats-web${id} \
        -e VIRTUAL_HOST=web${id}.bats \
        --expose 8000 \
        -p 8000 \
        -v $BATS_TEST_DIRNAME/fixtures/webservers/${id}/:/data \
        -w /data \
        python:3 \
        python -m http.server

    assert_success
    run curl --retry 5 --retry-delay 1 --silent --fail http://$(docker_ip):$(docker_port bats-web${id} 8000)/data
    assert_output web${id}
}
```

and prints out:

```
 ? start web container for http://1.bats/
   (from function `assert_output' in file test/lib/bats/batslib.bash, line 297,
    from function `start_web_container' in file test/suite.bats, line 40,
    in test file test/suite.bats, line 12)
     `start_web_container 1' failed
   bats-web1

   -- output differs --
   expected : web1
   actual   : ''
   --
```

---

which changes from this PR, the output becomes:

```
 ? start web container for http://1.bats/
   (from function `assert_output' in file test/lib/bats/batslib.bash, line 306,
    from function `start_web_container' in file test/suite.bats, line 40,
    in test file test/suite.bats, line 12)
     `start_web_container 1' failed
   bats-web1

   -- output differs --
   command  : curl --retry 5 --retry-delay 1 --silent --fail http://127.0.0.1:32832/data
   expected : web1
   actual   :
   --
```

which makes it as easy as copy/paste to reproduce the failing case by hand.

If you find this useful too, let me know and I'll complete this PR

### CODE REVIEW

**Comment by ztombol** [comment]
This is not a good idea for multiple reasons:
- Indiscriminate printing pollutes the output with potentially irrelevant information, which is exactly what the Standard Library, by design, tries to avoid.
- Bats' stack trace is a better place for this information.
  
  _One exception is `assert`, where the failed assertion is displayed by the function. This is not redundant however as the stack trace contains the verbatim command, and the assertion outputs the expression with variables expanded._

It may be possible to restructure the test so that its flexibility is preserved and Bats' stack trace captures the offending command.

I'm not sure if I understand the easy reproducibility. I understand that the command with its exact parameters may be useful, but the test environment (the docker container) should be destroyed by cleanup functions (e.g. `teadown`) before Bats exits. Making it impossible to just copy and paste the command and get the same outcome as in the failed test without exactly repeating the other commands, which are not displayed, too.

**Comment by thomasleveil** [comment]
I was finding useful to let the containers for failing tests alive so I could inspect their behavior manually later on. Maybe I should not use automated test for helping development but restrain their use for regression testing.

**Comment by ztombol** [comment]
I see, that's nice. There's no limit on what automated tests can be used for. You should use automated tests for whatever you want. :smile:

I gave it more thought and the stack trace won't work for this. You are right, it has to be the assertions that do the work. Doing it in a way that does not flood the output with irrelevant output is difficult however. I will look into it later this week.

**Comment by thomasleveil** [comment]
maybe such a behavior could be added optionally `bats --debug mytest.bats` ?

Such a debug mode could also make failing assertions print out the full `$output` even for single line matching.

**Pull request closed without merging**
